apiVersion: v1
kind: Service
metadata:
  name: churncast-fastapi-service
spec:
  type: NodePort
  selector:
    app: churncast-fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
