apiVersion: v1
kind: Service
metadata:
  name: churncast-mlflow-service
spec:
  type: NodePort
  selector:
    app: churncast-mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
