name: ChurnCast360 CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Conda environment exists
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda env list | grep churncast360

      - name: Verify Python and CUDA
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate churncast360
          python --version
          python -c "import xgboost as xgb; print(xgb.__version__)"
          nvidia-smi

      - name: Run tests
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate churncast360
          pytest tests/
